let isMongoConnected = false;

export const setMongoConnected = (status) => {
  isMongoConnected = status;
};

export const getMongoConnected = () => isMongoConnected;

export const memoryStore = {
  inquiries: [
    {
      _id: "inq-1",
      name: "Rajesh Kumar",
      email: "rajesh@techcorp.com",
      phone: "+91 98765 43210",
      service: "Website Development",
      message: "Looking for an e-commerce platform build with custom WooCommerce & payment gateway.",
      status: "New",
      createdAt: new Date(Date.now() - 3600000 * 5).toISOString(),
    },
    {
      _id: "inq-2",
      name: "Ananya Sharma",
      email: "ananya@growthlabs.io",
      phone: "+91 91234 56789",
      service: "Digital Marketing",
      message: "Need performance marketing and Meta/Google Ads campaign optimization.",
      status: "In Progress",
      createdAt: new Date(Date.now() - 3600000 * 24).toISOString(),
    },
  ],
  applications: [
    {
      _id: "app-1",
      jobId: "frontend-developer",
      jobTitle: "Frontend Developer",
      name: "Karthik Raja",
      email: "karthik.dev@gmail.com",
      phone: "+91 99887 76655",
      experience: "3 – 5 Years (Mid – Senior)",
      portfolioUrl: "https://github.com/karthik-dev",
      linkedinUrl: "https://linkedin.com/in/karthik",
      coverLetter: "Passionate React frontend engineer with 3 years of production experience in high-performance web applications.",
      resumeFileName: "Karthik_Raja_Resume.pdf",
      resumeData: "",
      resumeSize: "1.2 MB",
      status: "New",
      createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    },
  ],
  jobs: [
    {
      id: "job-1",
      _id: "job-1",
      slug: "frontend-developer",
      title: "Frontend Developer",
      dept: "Engineering",
      location: "Coimbatore / Remote",
      type: "Full-time",
      salary: "₹3L – ₹6L / year",
      palette: "cobalt",
      excerpt: "Turn beautiful designs into fast, accessible interfaces using React and modern CSS.",
      responsibilities: [
        "Build responsive UI with React, Next.js and modern CSS",
        "Optimise Core Web Vitals and page performance",
        "Collaborate with designers and backend engineers",
      ],
      requirements: [
        "2+ years building production React applications",
        "Strong HTML, CSS and JavaScript fundamentals",
      ],
      active: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: "job-2",
      _id: "job-2",
      slug: "wordpress-developer",
      title: "WordPress Developer",
      dept: "Engineering",
      location: "Coimbatore",
      type: "Full-time",
      salary: "₹2.5L – ₹5L / year",
      palette: "mint",
      excerpt: "Craft custom WordPress themes and plugins for clients in manufacturing, e-commerce and services.",
      responsibilities: [
        "Develop custom themes and plugins from scratch",
        "Set up e-commerce stores with WooCommerce",
      ],
      requirements: [
        "2+ years WordPress development experience",
        "Advanced PHP and MySQL knowledge",
      ],
      active: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: "job-3",
      _id: "job-3",
      slug: "ui-ux-designer",
      title: "UI/UX Designer",
      dept: "Design",
      location: "Coimbatore",
      type: "Full-time",
      salary: "₹3L – ₹6.5L / year",
      palette: "berry",
      excerpt: "Design intuitive digital products, wireframes, and design systems for enterprise software.",
      responsibilities: [
        "Conduct user research and create user flows",
        "Design high-fidelity UI components in Figma",
      ],
      requirements: [
        "Strong portfolio demonstrating Web & App UX",
        "Proficiency in Figma & prototyping tools",
      ],
      active: true,
      createdAt: new Date().toISOString(),
    },
  ],
  posts: [
    {
      _id: "post-1",
      slug: "why-every-business-needs-a-website-in-2026",
      title: "Why Every Business Still Needs a Website in 2026",
      category: "Web",
      date: "Aug 18, 2026",
      read: "5 min",
      palette: "cobalt",
      excerpt: "Social media borrows your audience; a website owns it. Here's why your own corner of the internet still matters more than ever.",
      image: "/images/cover-web.jpg",
      content: [
        { h: "The audience you rent vs the one you own" },
        { p: "Social platforms are powerful — but they can change their algorithm, their pricing or their rules overnight. A website is the one place where you control the experience, the content and the relationship. It's the home base every other channel points back to." },
        { h: "Credibility is decided in 5 seconds" },
        { p: "Before a customer buys, they check. A fast, clean and professional website tells them you're a serious business. In 2026 that first impression still happens on a company's own domain more than anywhere else." },
      ],
      author: "Nexprobyte Team",
      published: true,
      views: 342,
      createdAt: new Date().toISOString(),
    },
    {
      _id: "post-2",
      slug: "digital-marketing-that-actually-works-for-smes",
      title: "Digital Marketing That Actually Works for SMEs",
      category: "Marketing",
      date: "Jul 12, 2026",
      read: "4 min",
      palette: "mint",
      excerpt: "Forget vanity metrics. Here is the pragmatic playbook for small-to-mid companies wanting real revenue growth.",
      image: "/images/cover-marketing.jpg",
      content: [
        { h: "Focus on bottom-of-funnel first" },
        { p: "Don't spend your budget building awareness before your conversion mechanism is watertight. Start with search intent, high-converting landing pages, and lead follow-up automation." },
      ],
      author: "Nexprobyte Team",
      published: true,
      views: 215,
      createdAt: new Date().toISOString(),
    },
    {
      _id: "post-3",
      slug: "how-to-choose-the-right-digital-agency",
      title: "How to Choose the Right Digital Agency in India",
      category: "Business",
      date: "May 29, 2026",
      read: "6 min",
      palette: "ink",
      excerpt: "Before you hire an agency, you should know what to look for — and what to avoid. A practical guide for first-time buyers.",
      image: "/images/cover-business.jpg",
      content: [
        { h: "Look for process, not promises" },
        { p: "Avoid agencies that guarantee number one on Google or 10x sales overnight. The good ones talk about process: research, build, test, measure, improve." },
      ],
      author: "Nexprobyte Team",
      published: true,
      views: 189,
      createdAt: new Date().toISOString(),
    },
  ],
  about: {
    eyebrow: "WHO WE ARE",
    title: "We Build Digital Products That Scale",
    subtitle: "Nexprobyte Technologies is a digital agency based in Coimbatore, India. We combine technical rigor, thoughtful UI design, and data-driven marketing to help businesses grow.",
    story: "Founded with a vision to deliver enterprise-grade digital experiences for ambitious companies, Nexprobyte brings together engineering excellence and design precision.",
    mission: "To empower businesses with technology solutions that generate measurable revenue, elevate brand presence, and scale seamlessly.",
    vision: "To be the premier digital transformation partner for startups, SMEs, and global enterprises.",
    stats: [
      { label: "Projects Completed", value: "120+" },
      { label: "Client Satisfaction", value: "99%" },
      { label: "Team Specialists", value: "25+" },
      { label: "Years Experience", value: "6+" },
    ],
    values: [
      { title: "Engineering Excellence", description: "Clean code, robust architecture, and speed optimization in every project." },
      { title: "Client First", description: "Transparent communication, agile delivery, and long-term care plans." },
    ],
  },
};
